Init
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #1
Opened 2021-05-28 14:35 UTC by bouboumael

2021-05-28 14:36 UTC, glochlainn submitted a review, later dismissed

2021-05-28 14:36 UTC, RedPandore approved these changes, later dismissed

2021-05-28 14:37 UTC, RaphaelBS-WCS approved these changes, later dismissed
Approved!

2021-05-28 14:39 UTC, jaldabaoth-code submitted a review, later dismissed

2021-05-28 17:13 UTC, LucyMerlier requested changes
see comments

2021-05-28 17:13 UTC, LucyMerlier commented on templates/base.html.twig
> +		{% block footer %}{% endblock %}
indentation?

2021-05-28 17:13 UTC, LucyMerlier commented on templates/home/index.html.twig
> +{% block title %}{{ parent() }} - Home {% endblock %}
"Home"? Is this an english speaking website?

2021-05-28 17:13 UTC, LucyMerlier commented on templates/home/index.html.twig
>  {% extends 'base.html.twig' %}
so you have a "layout.html.twig", but this template extends "base.html.twig" directly?

2021-05-28 19:23 UTC, bouboumael commented on templates/home/index.html.twig
>  {% extends 'base.html.twig' %}
done

2021-05-28 19:31 UTC, jaldabaoth-code approved these changes

2021-05-29 11:59 UTC, LucyMerlier approved these changes

2021-05-29 11:59 UTC, merged