Fix home page admin
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #104
Opened 2021-06-22 13:29 UTC by RedPandore

2021-06-22 13:33 UTC, jaldabaoth-code submitted a review, later dismissed

2021-06-22 13:53 UTC, jaldabaoth-code submitted a review, later dismissed

2021-06-23 09:10 UTC, LucyMerlier requested changes
see comment

2021-06-23 09:10 UTC, LucyMerlier commented on templates/admin/index.html.twig
> +                                    <p class="card-text description">Créer un compte administrateurs.</p>
"adiministrateur" => singular, no "s"

2021-06-23 09:23 UTC, jaldabaoth-code approved these changes

2021-06-23 09:25 UTC, LucyMerlier approved these changes

2021-06-23 09:25 UTC, merged