Us04 02 ajouter form sur la carte, entité visitor trip et service Geocode
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #107
Opened 2021-06-22 14:58 UTC by RaphaelBS-WCS

ajout du form sur la carte, du service Geocode lié, de l'entité Visitor Trip.  
=> création d'un objet VisitorTrip

2021-06-22 15:08 UTC, jaldabaoth-code submitted a review, later dismissed

2021-06-23 07:53 UTC, LucyMerlier requested changes
see comments

2021-06-23 07:53 UTC, LucyMerlier commented on src/Service/Geocode.php
> +    public function getCoordonates(?string $location, string $layer = 'locality', string $country = 'FRA'): ?array
in english : "coord*i*nates"

2021-06-23 07:53 UTC, LucyMerlier commented on src/Service/Geocode.php
> +        throw new Exception('Le serice est temporairement indisponible');
"ser*v*ice"

2021-06-23 08:11 UTC, RaphaelBS-WCS commented on src/Service/Geocode.php
> +    public function getCoordonates(?string $location, string $layer = 'locality', string $country = 'FRA'): ?array
yes you're right

2021-06-23 08:11 UTC, RaphaelBS-WCS commented on src/Service/Geocode.php
> +        throw new Exception('Le serice est temporairement indisponible');
Oh yeah Thank you

2021-06-23 08:28 UTC, jaldabaoth-code approved these changes, later dismissed

2021-06-23 08:45 UTC, LucyMerlier requested changes
see comments

2021-06-23 08:45 UTC, LucyMerlier commented on src/Controller/HomeController.php
> +            $workCityCoordonate = $geocode->getCoordinates($workCity);
coord*i*nate

2021-06-23 08:45 UTC, LucyMerlier commented on src/Entity/VisitorTrip.php
> +}
coord*i*nates

2021-06-23 09:22 UTC, jaldabaoth-code approved these changes, later dismissed

2021-06-23 09:51 UTC, bouboumael approved these changes

2021-06-23 11:52 UTC, LucyMerlier approved these changes

2021-06-23 11:52 UTC, merged