S04 us05 company entity
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #120
Opened 2021-06-23 13:42 UTC by RedPandore

2021-06-23 14:38 UTC, jaldabaoth-code approved these changes

2021-06-23 14:45 UTC, jaldabaoth-code submitted a review, later dismissed

2021-06-25 08:00 UTC, LucyMerlier requested changes
see comments

2021-06-25 08:00 UTC, LucyMerlier commented on src/Entity/Company.php
> +    private string $adress;
in english : "address" => there's 2 "d"

2021-06-25 08:00 UTC, LucyMerlier commented on src/Entity/Company.php
> +     * @ORM\OneToMany(targetEntity=Subscription::class, mappedBy="company")
shouldn't this be a OneToOne?

2021-07-01 07:35 UTC, closed without merging