US26 user settings
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #125
Opened 2021-06-24 07:56 UTC by glochlainn

2021-06-24 08:24 UTC, bouboumael submitted a review, later dismissed

2021-06-25 08:09 UTC, LucyMerlier requested changes
see comment

2021-06-25 08:09 UTC, LucyMerlier commented on src/Form/ChangePasswordType.php
> +                    ]),
you already put validations as annotations in your entity file

2021-06-29 16:54 UTC, LucyMerlier requested changes
see comments

2021-06-29 16:54 UTC, LucyMerlier commented on src/Repository/ChangePasswordRepository.php
> +}
this file is useless

2021-07-04 08:06 UTC, RaphaelBS-WCS approved these changes
Approved

2021-07-05 08:05 UTC, LucyMerlier approved these changes

2021-07-05 08:05 UTC, merged