S01 us03 banner
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #14
Opened 2021-06-03 10:29 UTC by RedPandore

2021-06-03 10:55 UTC, bouboumael requested changes

2021-06-03 10:55 UTC, bouboumael commented on templates/includes/_header.html.twig
> +	<div class="jumbotron mb-0 d-flex justify-content-around jumbo_header ">
indentation refait un coup de formateur

2021-06-03 10:55 UTC, bouboumael commented on assets/styles/header.scss
> +    height: 50vh;
attention magic number

2021-06-03 10:55 UTC, bouboumael commented on assets/styles/header.scss
> +    padding: 1em;
attention magic number

2021-06-03 10:55 UTC, bouboumael commented on assets/styles/header.scss
> +    margin: 2em;
magic number

2021-06-03 10:55 UTC, bouboumael commented on templates/includes/_header.html.twig
> +    <a class="btn btn-primary btn-lg align-self-end mb-3" href="{{ path('home') }}">Découvrir Jobpermut</a>
du coup idem pour le <a>

2021-06-04 08:22 UTC, RaphaelBS-WCS approved these changes, later dismissed
Approved

2021-06-04 09:01 UTC, RaphaelBS-WCS approved these changes
Approved

2021-06-04 09:26 UTC, LucyMerlier approved these changes

2021-06-04 09:27 UTC, merged