S05 us27 admin testimony
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #147
Opened 2021-07-06 08:13 UTC by RedPandore

2021-07-06 09:01 UTC, bouboumael submitted a review, later dismissed

2021-07-06 09:15 UTC, LucyMerlier requested changes
see comments

2021-07-06 09:15 UTC, LucyMerlier commented on src/Controller/TestimonyController.php
> +        ]);
so an admin can add a review?

2021-07-06 09:15 UTC, LucyMerlier commented on src/Controller/TestimonyController.php
> +    }
so an admin can edit other people's testimonies?

2021-07-06 09:15 UTC, LucyMerlier commented on src/Entity/Testimony.php
> +    private ?User $users;
what? userS? plural?

2021-07-06 09:15 UTC, LucyMerlier commented on migrations/Version20210706080057.php
> +        $this->addSql('ALTER TABLE testimony ADD users_id INT NOT NULL, DROP user_id');
what? userS? plural?

2021-07-06 09:15 UTC, LucyMerlier commented on src/Form/TestimonyType.php
> +            ->add('commentary', TextType::class, ['attr' => ['placeholder' => 'You\'r text']]);
your*
+ no label?

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/_delete_form.html.twig
> +<form method="post" action="{{ path('testimony_delete', {'id': testimony.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
confirm message should be in french

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/_form.html.twig
> +    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
button should be in french

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/_delete_form.html.twig
> +    <button class="btn btn-danger m-2">Delete</button>
button should be in french

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/edit.html.twig
> +{% extends 'base.html.twig' %}
this extends base directly? not a layout?

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/edit.html.twig
> +{% endblock %}
whole document should be in french

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/index.html.twig
> +                    <td colspan="4">no records found</td>
should be in french

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/index.html.twig
> +{% extends 'base.html.twig' %}
this extends base directly? not a layout?

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/new.html.twig
> +{% extends 'base.html.twig' %}
this extends base directly? not a layout?

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/show.html.twig
> +{% extends 'base.html.twig' %}
this extends base directly? not a layout?

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/new.html.twig
> +{% endblock %}
whole document should be in french

2021-07-06 09:15 UTC, LucyMerlier commented on templates/testimony/show.html.twig
> +{% endblock %}
whole document should be in french

2021-07-06 11:34 UTC, bouboumael submitted a review, later dismissed

2021-07-06 11:47 UTC, LucyMerlier requested changes
see comment

2021-07-06 11:47 UTC, LucyMerlier commented on migrations/Version20210706093211.php
> +}
it feels like you actually don't need this migration since testimonies are already linked to a user => check with your classmates

2021-07-06 23:39 UTC, jaldabaoth-code approved these changes

2021-07-07 07:54 UTC, LucyMerlier approved these changes

2021-07-07 07:54 UTC, merged