Debug branch
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #38
Opened 2021-06-07 10:15 UTC by RedPandore

2021-06-07 21:12 UTC, bouboumael approved these changes, later dismissed

2021-06-08 11:49 UTC, LucyMerlier requested changes
see comments

2021-06-08 11:49 UTC, LucyMerlier commented on templates/includes/_presentation.html.twig
> +                            <div class="h3 text-muted list-subtitle">C'est une première étape non ?</div>
erm... don't get me wrong, those little comments are obviously funny, but you're gonna potentially present this  to your client, so you should keep it professionnal

2021-06-08 11:49 UTC, LucyMerlier commented on templates/includes/_presentation.html.twig
> +                            <div class="h3 text-muted list-subtitle">Et çà, une seconde étape non ?</div>
same as above

2021-06-08 11:49 UTC, LucyMerlier commented on templates/includes/_presentation.html.twig
> +                            <div class="h3 text-muted list-subtitle">Si je ne m'abuse, c'est la 3ème celle là ?</div>
same as above

2021-06-08 11:49 UTC, LucyMerlier commented on templates/includes/_presentation.html.twig
> +                            <div class="h3 text-muted list-subtitle">La quaaaatrièèèèème ?</div>
same as above

2021-06-08 11:49 UTC, LucyMerlier commented on templates/includes/_presentation.html.twig
> +                            <div class="h3 text-muted list-subtitle">C'est fini, plus d'étape ...</div>
same as above

2021-06-08 13:56 UTC, bouboumael submitted a review, later dismissed

2021-06-08 14:16 UTC, RedPandore commented on templates/includes/_presentation.html.twig
> +                            <div class="h3 text-muted list-subtitle">C'est une première étape non ?</div>
Not funny ....

2021-06-09 07:24 UTC, LucyMerlier requested changes
see comment

2021-06-09 07:24 UTC, LucyMerlier commented on templates/includes/_presentation.html.twig
> +                            <div class="h3 mt-0 text-muted list-subtitle">Notre dossier est analysée par l'équipe JobPermut</div>
typo : "analysé" * (because "dossier" is masculine)

2021-06-09 07:33 UTC, bouboumael approved these changes

2021-06-09 08:06 UTC, LucyMerlier approved these changes

2021-06-09 08:06 UTC, merged