Us17 01 profil
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #62
Opened 2021-06-11 07:52 UTC by glochlainn

2021-06-11 08:06 UTC, bouboumael approved these changes, later dismissed
ok just many files because autogenerate with symfony.

2021-06-14 09:57 UTC, LucyMerlier requested changes
see comments

2021-06-14 09:57 UTC, LucyMerlier commented on src/Entity/RegisteredUser.php
> +    private string $username;
you should add validations right away (using @ Assert annotations)

2021-06-14 09:57 UTC, LucyMerlier commented on src/Entity/Subscription.php
> +    private string $jobDescription;
you should add validations right away (using @ Assert annotations)

2021-06-14 09:57 UTC, LucyMerlier commented on src/Form/RegisteredUserType.php
> +            ->add('pseudo')
from what i understand, this property has been renamed "username"?

2021-06-14 09:57 UTC, LucyMerlier commented on src/Form/RegisteredUserType.php
> +            ->add('subscription')
i feel like you should have a form that creates the "User" entity associated with the "RegisteredUser" entity created here => "user" and "subscription" fields should not be here

2021-06-14 09:57 UTC, LucyMerlier commented on src/Form/RegisteredUserType.php
> +    }
you should add options right away when you create a form (labels, etc...)

2021-06-14 09:57 UTC, LucyMerlier commented on src/Form/RegisteredUserType.php
> +}
you are not using this form anywhere in your website yet

2021-06-14 09:57 UTC, LucyMerlier commented on src/Form/SubscriptionType.php
> +}
same comments as with other form class

2021-06-14 09:57 UTC, LucyMerlier commented on templates/profile/show.html.twig
> +						<p class="m-0 p-0">Orléans, Loiret</p>
isn't this specified dynamically thanks to the "jobAddress" property in "registeredUser"?

2021-06-14 09:57 UTC, LucyMerlier commented on templates/profile/show.html.twig
> +						<p class="m-0 p-0">Tours, Indre-et-Loire</p>
isn't this specified dynamically thanks to the "address" property in "registeredUser"?

2021-06-15 13:57 UTC, bouboumael approved these changes

2021-06-15 14:43 UTC, LucyMerlier approved these changes

2021-06-15 14:43 UTC, merged