S03 us13 inscription
WildCodeSchool/orleans-202103-php-project-jobpermut pull request #96
Opened 2021-06-21 10:16 UTC by jaldabaoth-code

2021-06-21 14:41 UTC, RedPandore approved these changes, later dismissed

2021-06-22 09:45 UTC, LucyMerlier requested changes
see comments

2021-06-22 09:45 UTC, LucyMerlier commented on migrations/Version20210621074133.php
> +}
doesn't this migration do exactly the same thing as the previous one?..

2021-06-22 09:45 UTC, LucyMerlier commented on migrations/Version20210621090216.php
> +
didn't you already have at least some of those tables?

2021-06-22 09:45 UTC, LucyMerlier commented on migrations/Version20210621095727.php
> +    }
this does the same as above

2021-06-22 09:45 UTC, LucyMerlier commented on migrations/Version20210621101252.php
> +    }
this does the same as above

2021-06-22 10:42 UTC, RaphaelBS-WCS approved these changes
Approved

2021-06-23 07:24 UTC, LucyMerlier approved these changes

2021-06-23 07:25 UTC, merged